# Generated by Django 4.0.2 on 2022-03-05 22:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attachments/User/image/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('object_type', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('file_object', models.FileField(upload_to='attachments/object_type_<django.db.models.fields.IntegerField>/object_id_<django.db.models.fields.IntegerField>/%Y_%m_%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('object_type', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=2007)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=2002)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=2001)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='coordination.department')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=2006)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordination.region')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('another_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modificate_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('archives', models.BooleanField(default=False)),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='coordination.subgroup')),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordination.volunteer')),
                ('object_type', models.IntegerField(default=1001)),
                ('max_number_of_people', models.IntegerField(default=0)),
                ('current_number_of_people', models.IntegerField(default=0)),
                ('free_space', models.IntegerField(default=0)),
                ('operating_range', models.IntegerField(default=0)),
                ('provides_transportation', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id')),
            ],
            bases=('coordination.volunteer',),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordination.volunteer')),
                ('object_type', models.IntegerField(default=1003)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Collection/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Collection/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Collection/<built-in function id>')),
            ],
            bases=('coordination.volunteer',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordination.volunteer')),
                ('object_type', models.IntegerField(default=1005)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Media/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Media/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Media/<built-in function id>')),
            ],
            bases=('coordination.volunteer',),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordination.volunteer')),
                ('object_type', models.IntegerField(default=1004)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Sponsor/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Sponsor/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Sponsor/<built-in function id>')),
            ],
            bases=('coordination.volunteer',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('volunteer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coordination.volunteer')),
                ('object_type', models.IntegerField(default=1002)),
                ('max_number_of_people', models.IntegerField(default=0)),
                ('operating_range', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Transport/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Transport/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Transport/<built-in function id>')),
            ],
            bases=('coordination.volunteer',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=1008)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modificate_date', models.DateTimeField(auto_now=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_accepted_by_user', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_sender_user', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status')),
            ],
        ),
        migrations.CreateModel(
            name='OneOffAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=1006)),
                ('name', models.CharField(max_length=150)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('max_number_of_people', models.IntegerField()),
                ('current_number_of_people', models.IntegerField()),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status')),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(default=1007)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('contactApp', models.CharField(blank=True, max_length=200, null=True)),
                ('residence_city', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=150, null=True)),
                ('residence_all', models.BooleanField(default=False)),
                ('destination_all', models.BooleanField(default=False)),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('pets', models.BooleanField(default=False)),
                ('pets_description', models.TextField(blank=True, default='', max_length=2000)),
                ('children_0_4', models.IntegerField(default=0)),
                ('children_5_12', models.IntegerField(default=0)),
                ('children_12_18', models.IntegerField(default=0)),
                ('adults', models.IntegerField(default=1)),
                ('disabled', models.IntegerField(default=0)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.department')),
                ('destination_voivodeship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_app_dest_voivodeship', to='coordination.voivodeship')),
                ('residence_voivodeship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_app_res_voivodeship', to='coordination.voivodeship')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_objects', to='coordination.subgroup')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordination.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='voivodeship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship'),
        ),
    ]
