# Generated by Django 3.2.12 on 2022-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transport'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Zgłoszenia', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Zbiórki', 'verbose_name_plural': 'Zbiórki'},
        ),
        migrations.AlterModelOptions(
            name='oneoffaction',
            options={'verbose_name': 'Akcje jednorazowe', 'verbose_name_plural': 'Akcje jednorazowe'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsorze', 'verbose_name_plural': 'Sponsorze'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Zadania', 'verbose_name_plural': 'Zadania'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transporty', 'verbose_name_plural': 'Transporty'},
        ),
        migrations.AddField(
            model_name='task',
            name='sended_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='object_type',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
