# Generated by Django 3.2.12 on 2022-03-11 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coordination', '0002_auto_20220311_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Mieszkanie', 'verbose_name_plural': 'Mieszkania'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Załącznik', 'verbose_name_plural': 'Załączniki'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Zbiórka', 'verbose_name_plural': 'Zbiórki'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Dział', 'verbose_name_plural': 'Działy'},
        ),
        migrations.AlterModelOptions(
            name='oneoffaction',
            options={'verbose_name': 'Akcja jednorazowa', 'verbose_name_plural': 'Akcje jednorazowe'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsorze'},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'Podgrupa', 'verbose_name_plural': 'Podgrupy'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transporty'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownice'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='attachment_1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='attachment_2',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='attachment_3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='children_12_18',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='attachment_1',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='attachment_2',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='attachment_3',
        ),
        migrations.RemoveField(
            model_name='media',
            name='attachment_1',
        ),
        migrations.RemoveField(
            model_name='media',
            name='attachment_2',
        ),
        migrations.RemoveField(
            model_name='media',
            name='attachment_3',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='attachment_1',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='attachment_2',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='attachment_3',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='attachment_1',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='attachment_2',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='attachment_3',
        ),
        migrations.AddField(
            model_name='application',
            name='children_13_17',
            field=models.IntegerField(default=0, verbose_name='Dzieci od 13 do 17-tu lat'),
        ),
        migrations.AddField(
            model_name='status',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='coordination.department', verbose_name='Dział'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id', verbose_name='Załąćznik 1'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id', verbose_name='Załąćznik 2'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Apartment/_id', verbose_name='Załąćznik 3'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Dostępny'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='current_number_of_people',
            field=models.IntegerField(default=0, verbose_name='Aktualna ilość zajętych miejsc'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='free_space',
            field=models.IntegerField(default=0, verbose_name='Wolne miejsca'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_number_of_people',
            field=models.IntegerField(default=0, verbose_name='Maksymalna ilość miejsc'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='operating_range',
            field=models.IntegerField(default=0, verbose_name='Zasięg km'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='provides_transportation',
            field=models.BooleanField(default=False, verbose_name='Zapewnia transport'),
        ),
        migrations.AlterField(
            model_name='application',
            name='adults',
            field=models.IntegerField(default=1, verbose_name='Dorosłe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Przebycia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>', verbose_name='Załąćznik 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>', verbose_name='Załąćznik 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Application/<built-in function id>', verbose_name='Załąćznik 3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='children_0_4',
            field=models.IntegerField(default=0, verbose_name='Dzieci do 4-ch lat'),
        ),
        migrations.AlterField(
            model_name='application',
            name='children_5_12',
            field=models.IntegerField(default=0, verbose_name='Dzieci od 5 do 12-tu lat'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contactApp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aplikacja do kontaktu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.department', verbose_name='Dział'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='application',
            name='destination_all',
            field=models.BooleanField(default=False, verbose_name='Miejsce docelowe - Cały kraj'),
        ),
        migrations.AlterField(
            model_name='application',
            name='destination_city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Miasto docelowe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='destination_voivodeship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_app_dest_voivodeship', to='coordination.voivodeship', verbose_name='Województwo docelowe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='disabled',
            field=models.IntegerField(default=0, verbose_name='Niepełnosprawni'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='application',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Zwirzęta domowe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='pets_description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Zwirzęta domowe Opis'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kontaktowy numer telefonu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='residence_all',
            field=models.BooleanField(default=False, verbose_name='Lokalizacja - Cały kraj'),
        ),
        migrations.AlterField(
            model_name='application',
            name='residence_city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Miasto przebywania'),
        ),
        migrations.AlterField(
            model_name='application',
            name='residence_voivodeship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_app_res_voivodeship', to='coordination.voivodeship', verbose_name='Województwo przebywania'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_objects', to='coordination.subgroup', verbose_name='Podgrupa'),
        ),
        migrations.AlterField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordination.volunteer', verbose_name='Wolonter'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_type',
            field=models.IntegerField(default=2003),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>', verbose_name='Załąćznik 1'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>', verbose_name='Załąćznik 2'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='attachments/OneOffAction/<built-in function id>', verbose_name='Załąćznik 3'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='current_number_of_people',
            field=models.IntegerField(verbose_name='Akualna ilość zajętych miejsc'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Zakończenia'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Początku'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Dział'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='max_number_of_people',
            field=models.IntegerField(verbose_name='Maksymalna ilość miejsc'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='oneoffaction',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='coordination.department', verbose_name='Dział'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_accepted_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba opracująca'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>', verbose_name='Załąćznik 1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>', verbose_name='Załąćznik 2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='attachments/Task/<built-in function id>', verbose_name='Załąćznik 3'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Utworzenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modificate_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_sender_user', to=settings.AUTH_USER_MODEL, verbose_name='Nadzorujący'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coordination.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Dostępny'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='max_number_of_people',
            field=models.IntegerField(default=0, verbose_name='Maksymalna ilość miejsc'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='operating_range',
            field=models.IntegerField(default=0, verbose_name='Zasięg km'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/User/image/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nazwa użytkownika'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voivodeship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='another_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='archives',
            field=models.BooleanField(default=False, verbose_name='Archiwum'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='modificate_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa dodatkowa'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='coordination.subgroup', verbose_name='Podgrupa'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.voivodeship', verbose_name='Województwo'),
        ),
    ]
