# Generated by Django 3.2.12 on 2022-03-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_auto_20220311_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='coordination.department', verbose_name='Dział'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='another_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa dodatkowa'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kontaktowy numer telefonu'),
        ),
    ]
